name: Android CI

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  notify-slack:
  
    runs-on: ubuntu-latest
  
    steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
                  {
          	        "mrkdwn_in": ["text"],
                      "color": "#36a64f",
                      "pretext": "Optional pre-text that appears above the attachment block",
                      "author_name": "author_name",
                      "author_link": "http://flickr.com/bobby/",
                      "author_icon": "https://placeimg.com/16/16/people",
                      "title": "title",
                      "title_link": "https://api.slack.com/",
                      "text": "Optional `text` that appears within the attachment",
                      "fields": [
                          {
                              "title": "A field's title",
                              "value": "This field's value",
                              "short": false
                          },
                          {
                              "title": "A short field's title",
                              "value": "A short field's value",
                              "short": true
                          },
                          {
                              "title": "A second short field's title",
                              "value": "A second short field's value",
                              "short": true
                          }
                      ],
                      "thumb_url": "http://placekitten.com/g/200/200",
                      "footer": "footer",
                      "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                      "ts": 123456789
                  }
              ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEV }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
       
  
